USE codeup_test_db;

CREATE TABLE IF NOT EXISTS CONTACTS (

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  number INT NOT NULL,
  email VARCHAR(255) NOT NULL,
  create_at VARCHAR(255) NOT NULL,
  updated_at VARCHAR(255) NOT NULL,
   PRIMARY KEY (id)
);